### ISSUE TITLE
Could not find DDI (Developer Disk Image)

### ISSUE THREAD

**Issue by sn8to** [CianApple/FileSystem#1]
I opened this up in Xcode and it already had errors that I had to fix. After fixing them, I tried to deploy the app to an iPad. This error appeared:
<img width="1364" alt="Xcode screenshot" src="https://cloud.githubusercontent.com/assets/17860556/16821851/4731c932-491e-11e6-8fe1-9e4aaad21f5a.png">

**Comment by sn8to** [comment]
Bump

**Comment by CianApple** [comment]
http://stackoverflow.com/questions/30736932/xcode-error-could-not-find-developer-disk-image

**Comment by CianApple** [comment]
Hi Glitch,

This is not an issue with the project. You have to add a disk image to the
iPhone simulator folder for it to work. Google it.
